# Site settings
title: Code Snippets
permalink: /:categories/:title
description: > # this means to ignore newlines until "baseurl:"
  Collection of code snippets
baseurl: "" # the subpath of your site, e.g. /blog
highlighter: pygments


# Build settings
markdown: redcarpet
paginate: 10
paginate_path: "page/:num"

gems:
  - jekyll-paginate